# Generated by Django 5.2.5 on 2025-09-15 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=100)),
                ('contactname', models.CharField(max_length=100)),
                ('contactemail', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default='Newstreet 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='companyname',
            field=models.CharField(default='New firma', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contactname',
            field=models.CharField(default='John Doe', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='England', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(default='john.doe@newfirma.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default='+358401234567', max_length=20),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('CMP', 'Completed'), ('CNC', 'Cancelled')], default='PND', max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
    ]
